import type { Metadata } from 'next';
import { Inter, Open_Sans, Russo_One } from 'next/font/google';

import { Box } from '@mui/material';
import { headerHeight, footerHeight } from './_noPages/config/layoutConfig';

import Header from './_noPages/views/header/Header';
import Footer from './_noPages/views/footer/Footer';
import './global.css';

const openSansFont = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-openSans',
});

const russoFont = Russo_One({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-russoFont',
});

const interFont = Inter({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-interFont',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${openSansFont.variable} ${russoFont.variable} ${interFont.variable}`}
      >
        <Box
          sx={{
            display: 'flex',
            flexDirection: 'column',
            width: '100vw',
            alignItems: 'center',
            backgroundColor: 'rgb(15 23 42)',
          }}
        >
          <Header />
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              maxWidth: '1021px',
              minHeight: `calc(100vh - ${headerHeight + footerHeight}px)`,
              padding: '30px 0',
            }}
          >
            <main>{children}</main>
          </Box>
          <Footer />
        </Box>
      </body>
    </html>
  );
}
